### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by kibotu** [rsxdalv/tts-generation-webui#100]
one click installer fails for M2

```sh

he following NEW packages will be INSTALLED:

  ffmpeg             pkgs/main/osx-arm64::ffmpeg-4.2.2-h04105a8_0
  gnutls             pkgs/main/osx-arm64::gnutls-3.6.15-h887c41c_0
  lame               pkgs/main/osx-arm64::lame-3.100-h1a28f6b_0
  libidn2            pkgs/main/osx-arm64::libidn2-2.3.4-h80987f9_0
  libopus            pkgs/main/osx-arm64::libopus-1.3-h1a28f6b_1
  libtasn1           pkgs/main/osx-arm64::libtasn1-4.19.0-h80987f9_0
  libunistring       pkgs/main/osx-arm64::libunistring-0.9.10-h1a28f6b_0
  libvpx             pkgs/main/osx-arm64::libvpx-1.10.0-hc377ac9_0
  nettle             pkgs/main/osx-arm64::nettle-3.7.3-h84b5d62_1
  openh264           pkgs/main/osx-arm64::openh264-1.8.0-h98b2900_0
  x264               pkgs/main/osx-arm64::x264-1!152.20180806-h1a28f6b_0

The following packages will be DOWNGRADED:

  cryptography                       41.0.2-py310h6204c90_0 --> 41.0.2-py310h6e31b35_0
  curl                                     8.1.1-h80987f9_1 --> 8.1.1-h80987f9_0
  git                               2.40.1-pl5340h6cf2078_1 --> 2.40.1-pl5340h3afa44c_1
  krb5                                    1.20.1-hf3e1bf2_1 --> 1.19.4-h8380606_0
  libcurl                                  8.1.1-h3e2b118_1 --> 8.1.1-h0f1d93c_0
  libnghttp2                              1.52.0-h62f6fdd_1 --> 1.52.0-h10c0552_1
  libssh2                                 1.10.0-h02f6b3c_2 --> 1.10.0-h449679c_2
  openssl                                  3.0.9-h1a28f6b_0 --> 1.1.1u-h1a28f6b_0
  python                                 3.10.12-hb885b13_0 --> 3.10.12-hc0d8a6c_0

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Traceback (most recent call last):
  File "/Users/kibotu/Documents/repos/ai/tts-generation-webui/webui.py", line 96, in <module>
    install_dependencies()
  File "/Users/kibotu/Documents/repos/ai/tts-generation-webui/webui.py", line 60, in install_dependencies
    update_dependencies()
  File "/Users/kibotu/Documents/repos/ai/tts-generation-webui/webui.py", line 68, in update_dependencies
    os.chdir("tts-generation-webui")
FileNotFoundError: [Errno 2] No such file or directory: 'tts-generation-webui'
```

**Comment by rsxdalv** [comment]
Seems like git clone failed. Could you please tell me what is inside the directory now?

**Comment by w121211** [comment]
Encounter the same error on my Macbook M1.

Solved by creating a conda environment and activate.
```
$ conda create -n yourenvname python=3.10
$ conda activate yourenvname
```

**Comment by rsxdalv** [comment]
> Encounter the same error on my Macbook M1.
> 
> Solved by creating a conda environment and activate.
> 
> ```
> $ conda create -n yourenvname python=3.10
> $ conda activate yourenvname
> ```

Thanks for the solution! It's strange that the one click installer does not create a conda environment successfully. It's supposed to do those two commands.

**Comment by rsxdalv** [comment]
I saw an issue where the "git clone https://github.com/rsxdalv/tts-generation-webui" command in installer just doesn't happen.
Current workaround is:
after running `start_macos.sh` and it failing:
run `cmd_macos.sh`
inside this shell do `git clone https://github.com/rsxdalv/tts-generation-webui`
then run `update_macos.sh`

**Comment by Maki9009** [comment]
> I saw an issue where the "git clone https://github.com/rsxdalv/tts-generation-webui" command in installer just doesn't happen. Current workaround is: after running `start_macos.sh` and it failing: run `cmd_macos.sh` inside this shell do `git clone https://github.com/rsxdalv/tts-generation-webui` then run `update_macos.sh`

any chance if getting fixed without a work around, cuz i think cmd_macos.sh is also failing for me

**Comment by Maki9009** [comment]
the workaround didnt work for me
