### ISSUE TITLE
Error Generating Voice Samples using Tortoise

### ISSUE THREAD

**Issue by AdroitProgrammer** [rsxdalv/tts-generation-webui#106]
First, thank you so much for making this! I have been using all of the tools separately so I was happy to discover one home for all of the tools. I want to generate voices using Tortoise, but I am getting an error on Windows 11 with a Nvidia 3090. Not that I think it matters, because it seems to be a key error in the dictionary.

Generating tortoise with params:
TortoiseParameters(
    text='Hello, this is a new sound.',
    voice='random',
    preset='ultra_fast',
    seed=-1.0,
    cvvp_amount=0.0,
    split_prompt=False,
    num_autoregressive_samples=16,
    diffusion_iterations=30,
    temperature=0.8,
    length_penalty=1.0,
    repetition_penalty=2.0,
    top_p=0.8,
    max_mel_tokens=500,
    cond_free=True,
    cond_free_k=2,
    diffusion_temperature=1.0,
    model='Default'
)
Traceback (most recent call last):
  File "C:\Users\Jonathan\Documents\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Jonathan\Documents\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\Users\Jonathan\Documents\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\Jonathan\Documents\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\Jonathan\Documents\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\Jonathan\Documents\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Jonathan\Documents\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Jonathan\Documents\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Jonathan\Documents\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\Jonathan\Documents\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\generation_tab_tortoise.py", line 162, in gen
    yield from generate_tortoise_long(
  File "C:\Users\Jonathan\Documents\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\gen_tortoise.py", line 188, in generate_tortoise_long
    datas = generate_tortoise(
  File "C:\Users\Jonathan\Documents\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\gen_tortoise.py", line 100, in generate_tortoise
    tts = get_tts()
  File "C:\Users\Jonathan\Documents\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\gen_tortoise.py", line 77, in get_tts
    MODEL = TextToSpeech(
  File "C:\Users\Jonathan\Documents\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\tortoise\api.py", line 231, in __init__
    self.autoregressive.load_state_dict(torch.load(get_model_path('autoregressive.pth', models_dir)))
  File "C:\Users\Jonathan\Documents\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UnifiedVoice:
        Unexpected key(s) in state_dict: "gpt.h.0.attn.bias", "gpt.h.0.attn.masked_bias", "gpt.h.1.attn.bias", "gpt.h.1.attn.masked_bias", "gpt.h.2.attn.bias", "gpt.h.2.attn.masked_bias", "gpt.h.3.attn.bias", "gpt.h.3.attn.masked_bias", "gpt.h.4.attn.bias", "gpt.h.4.attn.masked_bias", "gpt.h.5.attn.bias", "gpt.h.5.attn.masked_bias", "gpt.h.6.attn.bias", "gpt.h.6.attn.masked_bias", "gpt.h.7.attn.bias", "gpt.h.7.attn.masked_bias", "gpt.h.8.attn.bias", "gpt.h.8.attn.masked_bias", "gpt.h.9.attn.bias", "gpt.h.9.attn.masked_bias", "gpt.h.10.attn.bias", "gpt.h.10.attn.masked_bias", "gpt.h.11.attn.bias", "gpt.h.11.attn.masked_bias", "gpt.h.12.attn.bias", "gpt.h.12.attn.masked_bias", "gpt.h.13.attn.bias", "gpt.h.13.attn.masked_bias", "gpt.h.14.attn.bias", "gpt.h.14.attn.masked_bias", "gpt.h.15.attn.bias", "gpt.h.15.attn.masked_bias", "gpt.h.16.attn.bias", "gpt.h.16.attn.masked_bias", "gpt.h.17.attn.bias", "gpt.h.17.attn.masked_bias", "gpt.h.18.attn.bias", "gpt.h.18.attn.masked_bias", "gpt.h.19.attn.bias", "gpt.h.19.attn.masked_bias", "gpt.h.20.attn.bias", "gpt.h.20.attn.masked_bias", "gpt.h.21.attn.bias", "gpt.h.21.attn.masked_bias", "gpt.h.22.attn.bias", "gpt.h.22.attn.masked_bias", "gpt.h.23.attn.bias", "gpt.h.23.attn.masked_bias", "gpt.h.24.attn.bias", "gpt.h.24.attn.masked_bias", "gpt.h.25.attn.bias", "gpt.h.25.attn.masked_bias", "gpt.h.26.attn.bias", "gpt.h.26.attn.masked_bias", "gpt.h.27.attn.bias", "gpt.h.27.attn.masked_bias", "gpt.h.28.attn.bias", "gpt.h.28.attn.masked_bias", "gpt.h.29.attn.bias", "gpt.h.29.attn.masked_bias".

**Comment by rsxdalv** [comment]
Tortoise is like ultra sensitive about pip transformers package version.
Please, could you verify which version you have with cmd_windows.bat and
then `pip show transformers`?

**Comment by AdroitProgrammer** [comment]
Thanks for getting back to me so quickly! The output is below.

pip show transformers
Name: transformers
Version: 4.31.0
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: c:\users\jonathan\documents\one-click-installers-tts-6.0\installer_files\env\lib\site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: audiocraft, audiolm-pytorch, bark-hubert-quantizer, suno-bark, TorToiSe

**Comment by rsxdalv** [comment]
Please try `pip install transformers==4.29.2`
And let me know if something else is affected by it. To best of
my knowledge, the other projects should be good with 4.29.2 but things can
and do change.

**Comment by AdroitProgrammer** [comment]
Good news and bad news. Tortoise works! But it killed Music Gen. The error I received is below 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
audiocraft 1.0.0 requires hydra-core>=1.1, but you have hydra-core 1.0.7 which is incompatible.
audiocraft 1.0.0 requires transformers>=4.31.0, but you have transformers 4.29.2 which is incompatible.

**Comment by rsxdalv** [comment]
Thanks for the report!
Oh, yeah it's impossible to avoid errors, but it might still work.

**Comment by AdroitProgrammer** [comment]
I believe they are still in conflict with each other. I was prompted with an error when I tried to click on the music Gen tab. It had an exclamation point on top of the tab with a button prompting me to install music gen. It gave me the error "Error: cannot import name ‘EncodecModel’ from ‘transformers’ (C:\Users\Jonathan
![Screenshot 2023-08-03 121723](https://github.com/rsxdalv/tts-generation-webui/assets/567552/8c5fde13-86ae-4a40-acf4-27bdd3a0dc3b)
\Documents\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\transformers_init_.py)"  When I installed MusicGen by pressing the button, it installed the old version of the transformers. Fixing MusicGen, but breaking Tortoise. Thank you for all of this debugging help. I do already have tortoise installed so I am in no rush.

**Comment by MiYakuGaming** [comment]
I got the same exact error myself, and when trying to update through update_windows.bat, it just reverts transformers back to 4.30 as before.
Is there going to be a fix to this?

**Comment by rsxdalv** [comment]
> I got the same exact error myself, and when trying to update through update_windows.bat, it just reverts transformers back to 4.31 as before. Is there going to be a fix to this?

Yes, tortoise is being fixed.

For now if you install the old transformers version and don't update yet it will be ok. I will update this issue once Tortoise issue is resolved.
