### ISSUE TITLE
Tortoise Deepspeed Error on Colab

### ISSUE THREAD

**Issue by BankNatchapol** [rsxdalv/tts-generation-webui#107]
This error occurs when i was trying to generate audio using Tortoise on the provided Google Colab.

```
 0% 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "/content/tts-generation-webui/src/tortoise/generation_tab_tortoise.py", line 162, in gen
    yield from generate_tortoise_long(
  File "/content/tts-generation-webui/src/tortoise/gen_tortoise.py", line 188, in generate_tortoise_long
    datas = generate_tortoise(
  File "/content/tts-generation-webui/src/tortoise/gen_tortoise.py", line 101, in generate_tortoise
    result, state = tts.tts_with_preset(
  File "/usr/local/lib/python3.10/dist-packages/tortoise/api.py", line 334, in tts_with_preset
    return self.tts(text, **settings)
  File "/usr/local/lib/python3.10/dist-packages/tortoise/api.py", line 418, in tts
    codes = autoregressive.inference_speech(auto_conditioning, text_tokens,
  File "/usr/local/lib/python3.10/dist-packages/tortoise/models/autoregressive.py", line 533, in inference_speech
    gen = self.inference_model.generate(inputs, bos_token_id=self.start_mel_token, pad_token_id=self.stop_mel_token, eos_token_id=self.stop_mel_token,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1565, in generate
    return self.sample(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2612, in sample
    outputs = self(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tortoise/models/autoregressive.py", line 147, in forward
    transformer_outputs = self.transformer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gpt2/modeling_gpt2.py", line 900, in forward
    outputs = block(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/model_implementations/transformers/ds_transformer.py", line 166, in forward
    target_dtype = torch.half if self.dtype == torch.int8 else self.dtype
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DeepSpeedGPTInference' object has no attribute 'dtype'. Did you mean: 'type'?
```

<img width="388" alt="image" src="https://github.com/rsxdalv/tts-generation-webui/assets/53829777/34a2f424-0f6f-4825-ac3d-78780d5befae">

Without deepspeed tick, it's working fine. 🤔

**Comment by rsxdalv** [comment]
Thanks for letting me know, I will forward it to the tortoise repo.

**Comment by rsxdalv** [comment]
This might be the solution/workaround by https://github.com/TomOerlemans:

> I have the same problem with the latest version of DeepSpeed (v0.10.0). Fortunately, the version specified in requirements.txt does work for me:
> 
> ```
> pip uninstall deepspeed
> pip install deepspeed==0.8.3
> ```

**Comment by BankNatchapol** [comment]
it's work! Thank you.
