### ISSUE TITLE
validation error for PredictBody

### ISSUE THREAD

**Issue by BankNatchapol** [rsxdalv/tts-generation-webui#110]
I got this error when trying to run python server.py on Ubuntu 20.04. Thank you in advanced!

```
Loading extensions:
Loaded extension: callback_save_generation_musicgen_ffmpeg
Loaded extension: callback_save_generation_ffmpeg
Loaded extension: empty_extension
Loaded 2 callback_save_generation extensions.
Loaded 1 callback_save_generation_musicgen extensions.
Failed to load voice clone demo
No module named 'bark_hubert_quantizer'
Failed to load musicgen demo
No module named 'audiocraft'
Failed to load rvc demo
No module named 'rvc_beta'
Failed to load demucs demo
No module named 'demucs'
Starting Gradio server...
Gradio interface options:
  inline:               False
  inbrowser:            True
  share:                False
  debug:                False
  enable_queue:         True
  max_threads:          40
  auth:                 None
  auth_message:         None
  prevent_thread_lock:  False
  show_error:           False
  server_name:          0.0.0.0
  server_port:          80
  show_tips:            False
  height:               500
  width:                100%
  favicon_path:         None
  ssl_keyfile:          None
  ssl_certfile:         None
  ssl_keyfile_password: None
  ssl_verify:           True
  quiet:                True
  show_api:             True
  file_directories:     None
  _frontend:            True
Running on local URL:  http://0.0.0.0:80
Task exception was never retrieved
future: <Task finished name='zonoqduhrbe_61' coro=<Queue.process_events() done, defined at /usr/local/lib/python3.10/dist-packages/gradio/queueing.py:342> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['exception=1 va...on_hash': 'zonoqduhrbe'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 346, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 219, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 448, in get_message
    return PredictBody(**data), True
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['exception=1 va...on_hash': 'zonoqduhrbe'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
```

**Comment by rsxdalv** [comment]
Seems like a deep gradio error, I think I have seen these kinds of errors when there's a version mismatch or some other bigger failure.

Looking at the log:
```
Failed to load voice clone demo
No module named 'bark_hubert_quantizer'
Failed to load musicgen demo
No module named 'audiocraft'
Failed to load rvc demo
No module named 'rvc_beta'
Failed to load demucs demo
No module named 'demucs'
```

I'd like to ask - did you use the one click installers?
It seems that many things were not installed.
There are multiple requirements.txt files, all of them are invoked using the update.py script.

**Comment by BankNatchapol** [comment]
I installed using the same way as in google colab. I just realize that i should use one click installer 😅. Thank you very much for your answer!
