### ISSUE TITLE
AudioGen.generate() got an unexpected keyword argument 'return_tokens'

### ISSUE THREAD

**Issue by MrMondragon** [rsxdalv/tts-generation-webui#111]
Sorry, posted without description on the first try:

Below follows the log I get when I try to use audiogen inside the web-ui. Anyone else seeing this? Any known workarounds?

Traceback (most recent call last):
  File "C:\MusicGen\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\MusicGen\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\MusicGen\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\MusicGen\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\MusicGen\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\MusicGen\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\MusicGen\one-click-installers-tts-6.0\tts-generation-webui\src\musicgen\musicgen_tab.py", line 181, in generate
    output, tokens = MODEL.generate(
TypeError: AudioGen.generate() got an unexpected keyword argument 'return_tokens'

**Comment by rsxdalv** [comment]
Please try the newest update

**Comment by MrMondragon** [comment]
Works perfectly now! Thanks!!
