### ISSUE TITLE
new install error and TTS Generation not working

### ISSUE THREAD

**Issue by Kedaranatha** [rsxdalv/tts-generation-webui#119]
window 11, 3090
TTS Generation not working

install errors: 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tortoise 2.5.0 requires transformers==4.29.2, but you have transformers 4.31.0 which is incompatible.
audiocraft 1.0.0 requires hydra-core>=1.1, but you have hydra-core 1.0.7 which is incompatible.

If im installing transformers to 4.29.2 then Bark is not working at all!

 TTS Generation error:
 
 Traceback (most recent call last):
  File "C:\Users\Kedar\AI_APPS\tts-generation-webui\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Kedar\AI_APPS\tts-generation-webui\venv\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\Users\Kedar\AI_APPS\tts-generation-webui\venv\lib\site-packages\gradio\blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\Kedar\AI_APPS\tts-generation-webui\venv\lib\site-packages\gradio\utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\Kedar\AI_APPS\tts-generation-webui\venv\lib\site-packages\gradio\utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\Kedar\AI_APPS\tts-generation-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Kedar\AI_APPS\tts-generation-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Kedar\AI_APPS\tts-generation-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Kedar\AI_APPS\tts-generation-webui\venv\lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\Kedar\AI_APPS\tts-generation-webui\src\tortoise\generation_tab_tortoise.py", line 162, in gen
    yield from generate_tortoise_long(
  File "C:\Users\Kedar\AI_APPS\tts-generation-webui\src\tortoise\gen_tortoise.py", line 190, in generate_tortoise_long
    datas = generate_tortoise(
  File "C:\Users\Kedar\AI_APPS\tts-generation-webui\src\tortoise\gen_tortoise.py", line 102, in generate_tortoise
    tts = get_tts()
  File "C:\Users\Kedar\AI_APPS\tts-generation-webui\src\tortoise\gen_tortoise.py", line 78, in get_tts
    MODEL = TextToSpeech(
  File "C:\Users\Kedar\AI_APPS\tts-generation-webui\venv\lib\site-packages\tortoise\api.py", line 231, in __init__
    self.autoregressive.load_state_dict(torch.load(get_model_path('autoregressive.pth', models_dir)))
  File "C:\Users\Kedar\AI_APPS\tts-generation-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UnifiedVoice:
        Unexpected key(s) in state_dict: "gpt.h.0.attn.bias", "gpt.h.0.attn.masked_bias", "gpt.h.1.attn.bias", "gpt.h.1.attn.masked_bias", "gpt.h.2.attn.bias", "gpt.h.2.attn.masked_bias", "gpt.h.3.attn.bias", "gpt.h.3.attn.masked_bias", "gpt.h.4.attn.bias", "gpt.h.4.attn.masked_bias", "gpt.h.5.attn.bias", "gpt.h.5.attn.masked_bias", "gpt.h.6.attn.bias", "gpt.h.6.attn.masked_bias", "gpt.h.7.attn.bias", "gpt.h.7.attn.masked_bias", "gpt.h.8.attn.bias", "gpt.h.8.attn.masked_bias", "gpt.h.9.attn.bias", "gpt.h.9.attn.masked_bias", "gpt.h.10.attn.bias", "gpt.h.10.attn.masked_bias", "gpt.h.11.attn.bias", "gpt.h.11.attn.masked_bias", "gpt.h.12.attn.bias", "gpt.h.12.attn.masked_bias", "gpt.h.13.attn.bias", "gpt.h.13.attn.masked_bias", "gpt.h.14.attn.bias", "gpt.h.14.attn.masked_bias", "gpt.h.15.attn.bias", "gpt.h.15.attn.masked_bias", "gpt.h.16.attn.bias", "gpt.h.16.attn.masked_bias", "gpt.h.17.attn.bias", "gpt.h.17.attn.masked_bias", "gpt.h.18.attn.bias", "gpt.h.18.attn.masked_bias", "gpt.h.19.attn.bias", "gpt.h.19.attn.masked_bias", "gpt.h.20.attn.bias", "gpt.h.20.attn.masked_bias", "gpt.h.21.attn.bias", "gpt.h.21.attn.masked_bias", "gpt.h.22.attn.bias", "gpt.h.22.attn.masked_bias", "gpt.h.23.attn.bias", "gpt.h.23.attn.masked_bias", "gpt.h.24.attn.bias", "gpt.h.24.attn.masked_bias", "gpt.h.25.attn.bias", "gpt.h.25.attn.masked_bias", "gpt.h.26.attn.bias", "gpt.h.26.attn.masked_bias", "gpt.h.27.attn.bias", "gpt.h.27.attn.masked_bias", "gpt.h.28.attn.bias", "gpt.h.28.attn.masked_bias", "gpt.h.29.attn.bias", "gpt.h.29.attn.masked_bias".

**Comment by rsxdalv** [comment]
Yes, you are exactly right that it's transformers which cause this issue. Thank you for debugging and checking in!
Recently Bark and AudioCraft decided to use encodec from transformers while transformers keeps breaking their Tortoise compatibility pretty frequently, so Tortoise needs to be changed.

Currently I am basically alone trying to fix tortoise to make it work with 4.31.0...
There are several issues in this repo that detail more about this case.

**Comment by rsxdalv** [comment]
Should work with newest update
