### ISSUE TITLE
RuntimeError: The specified pointer resides on host memory and is not registered with any CUDA device.

### ISSUE THREAD

**Issue by BankNatchapol** [rsxdalv/tts-generation-webui#120]
The one-click installer version tortoise tts is working fine yesterday, but after running update_linux.sh this error occurs.
It only occurs on my custom model with deepspeed. The default model is OK.

```
Traceback (most recent call last):
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "/root/one-click-installers-tts-6.0/tts-generation-webui/src/tortoise/generation_tab_tortoise.py", line 162, in gen
    yield from generate_tortoise_long(
  File "/root/one-click-installers-tts-6.0/tts-generation-webui/src/tortoise/gen_tortoise.py", line 190, in generate_tortoise_long
    datas = generate_tortoise(
  File "/root/one-click-installers-tts-6.0/tts-generation-webui/src/tortoise/gen_tortoise.py", line 103, in generate_tortoise
    result, state = tts.tts_with_preset(
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/tortoise/api.py", line 334, in tts_with_preset
    return self.tts(text, **settings)
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/tortoise/api.py", line 418, in tts
    codes = autoregressive.inference_speech(auto_conditioning, text_tokens,
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/tortoise/models/autoregressive.py", line 533, in inference_speech
    gen = self.inference_model.generate(inputs, bos_token_id=self.start_mel_token, pad_token_id=self.stop_mel_token, eos_token_id=self.stop_mel_token,
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 1565, in generate
    return self.sample(
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/transformers/generation/utils.py", line 2612, in sample
    outputs = self(
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/tortoise/models/autoregressive.py", line 147, in forward
    transformer_outputs = self.transformer(
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 900, in forward
    outputs = block(
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/deepspeed/model_implementations/transformers/ds_transformer.py", line 157, in forward
    self.attention(input,
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/ds_attention.py", line 128, in forward
    context_layer, key_layer, value_layer = self.compute_attention(
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/ds_attention.py", line 82, in compute_attention
    attn_key_value = self.score_context_func(
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/op_binding/softmax_context.py", line 34, in forward
    output = self.softmax_context_func(query_key_value,
RuntimeError: The specified pointer resides on host memory and is not registered with any CUDA device.
```
I also tried `deepspeed==0.8.3` but it still not works.

**Comment by BankNatchapol** [comment]
Somehow it dissapear

**Comment by rsxdalv** [comment]
Thanks for the report, though it was temporary it might happen again.
