### ISSUE TITLE
Update fails on macOS when installing rvc-beta

### ISSUE THREAD

**Issue by kuglee** [rsxdalv/tts-generation-webui#122]
HI,

Thanks for the project.

I have an issue with the update script. It fails on installing rvc-beta:

```
Building wheels for collected packages: torchcrepe, rvc-beta
  Building wheel for torchcrepe (setup.py) ... done
  Created wheel for torchcrepe: filename=torchcrepe-0.0.20-py3-none-any.whl size=72326242 sha256=81f13868868e84507f420b02c8722c6fca47a65b45adf65b500a6c92d82b3b5b
  Stored in directory: /private/var/folders/3z/sn1s5sd168579mqdhyvyq3gh0000gn/T/pip-ephem-wheel-cache-aly64qkb/wheels/4a/7c/9f/170aad22b22218ca80febc6cf9f321b105adfed5c6930233fe
  Building wheel for rvc-beta (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for rvc-beta (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "/Users/kuglee/Downloads/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/kuglee/Downloads/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/kuglee/Downloads/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/3z/sn1s5sd168579mqdhyvyq3gh0000gn/T/pip-build-env-n56ce437/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 57, in build_wheel
          return WheelBuilder.make_in(
        File "/private/var/folders/3z/sn1s5sd168579mqdhyvyq3gh0000gn/T/pip-build-env-n56ce437/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 88, in make_in
          wb.build(target_dir=directory)
        File "/private/var/folders/3z/sn1s5sd168579mqdhyvyq3gh0000gn/T/pip-build-env-n56ce437/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 124, in build
          self._copy_module(zip_file)
        File "/private/var/folders/3z/sn1s5sd168579mqdhyvyq3gh0000gn/T/pip-build-env-n56ce437/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 235, in _copy_module
          to_add = self.find_files_to_add()
        File "/private/var/folders/3z/sn1s5sd168579mqdhyvyq3gh0000gn/T/pip-build-env-n56ce437/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/builder.py", line 200, in find_files_to_add
          if self.is_excluded(
        File "/private/var/folders/3z/sn1s5sd168579mqdhyvyq3gh0000gn/T/pip-build-env-n56ce437/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/builder.py", line 143, in is_excluded
          if exclude_path.as_posix() in self.find_excluded_files(fmt=self.format):
        File "/private/var/folders/3z/sn1s5sd168579mqdhyvyq3gh0000gn/T/pip-build-env-n56ce437/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/builder.py", line 111, in find_excluded_files
          vcs_ignored_files = set(vcs.get_ignored_files()) if vcs else set()
        File "/private/var/folders/3z/sn1s5sd168579mqdhyvyq3gh0000gn/T/pip-build-env-n56ce437/overlay/lib/python3.10/site-packages/poetry/core/vcs/git.py", line 340, in get_ignored_files
          output = self.run(*args)
        File "/private/var/folders/3z/sn1s5sd168579mqdhyvyq3gh0000gn/T/pip-build-env-n56ce437/overlay/lib/python3.10/site-packages/poetry/core/vcs/git.py", line 373, in run
          subprocess.check_output(
        File "/Users/kuglee/Downloads/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/Users/kuglee/Downloads/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['git', '--git-dir', '/private/var/folders/3z/sn1s5sd168579mqdhyvyq3gh0000gn/T/pip-install-pvdanmj5/rvc-beta_5aa98684fc0f4a95a0f6ca810d0759d9/.git', '--work-tree', '/private/var/folders/3z/sn1s5sd168579mqdhyvyq3gh0000gn/T/pip-install-pvdanmj5/rvc-beta_5aa98684fc0f4a95a0f6ca810d0759d9', 'ls-files', '--others', '-i', '--exclude-standard']' returned non-zero exit status 128.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rvc-beta
Successfully built torchcrepe
Failed to build rvc-beta
ERROR: Could not build wheels for rvc-beta, which is required to install pyproject.toml-based projects
Failed to install RVC dependencies

Done!
```

**Comment by rsxdalv** [comment]
Thanks for reporting!

The rest of the project should be functional even if RVC failed.

Also, the error seems quite arbitrary. Perhaps updating again might make it
succeed this time (main part is for pip install -r requirements_rvc.txt
within conda to be ran again).

**Comment by kuglee** [comment]
Thank!

Tried to run within conda but got the same error:
```
pip install -r tts-generation-webui/requirements_rvc.txt
```

As you said the rest is working fine. I didn't want to use that anyway.
