### ISSUE TITLE
MusicGen Tab - Multiband Diffusion error

### ISSUE THREAD

**Issue by Magenta-6** [rsxdalv/tts-generation-webui#141]
Hi there.
I tried the updated version to check out what was new.
The MBD addition looks like a great feature if I could get it to work.

There seem to be a few references to "validate_and_normalize_key"
Does this mean I need to get a HuggingFace Token or something to activate this?

thanks in advance.

+++++++++++++++++++++++++++++++++++++++++++++++++++
Running on local URL:  http://0.0.0.0:7860
Loading model facebook/musicgen-small
Generating: ''' light dinner music reggae '''
Parameters:
text : light dinner music reggae
melody : None
model : facebook/musicgen-small
duration : 10
topk : 250
topp : 0
temperature : 1
cfg_coef : 3
seed : 3722894421
use_multi_band_diffusion : False
Generated in 18.538 seconds
Saving generation to outputs\2023-08-19_22-19-46__musicgen__light_dinner_music_r\2023-08-19_22-19-46__musicgen__light_dinner_music_r.ogg
Saved generation to outputs\2023-08-19_22-19-46__musicgen__light_dinner_music_r\2023-08-19_22-19-46__musicgen__light_dinner_music_r.ogg
C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\gradio\processing_utils.py:171: UserWarning: Trying to convert audio automatically from float32 to 16-bit int format.
  warnings.warn(warning.format(data.dtype))
Generating: ''' light dinner music reggae '''
Parameters:
text : light dinner music reggae
melody : None
model : facebook/musicgen-small
duration : 10
topk : 250
topp : 0
temperature : 1
cfg_coef : 3
seed : 648156559
use_multi_band_diffusion : True
Generated in 16.806 seconds
Traceback (most recent call last):
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\omegaconf\dictconfig.py", line 303, in __getattr__
    return self._get_impl(key=key, default_value=DEFAULT_VALUE_MARKER)
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\omegaconf\dictconfig.py", line 361, in _get_impl
    node = self._get_node(key=key)
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\omegaconf\dictconfig.py", line 375, in _get_node
    key = self._validate_and_normalize_key(key)
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\omegaconf\dictconfig.py", line 222, in _validate_and_normalize_key
    return self._s_validate_and_normalize_key(self._metadata.key_type, key)
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\omegaconf\dictconfig.py", line 241, in _s_validate_and_normalize_key
    elif issubclass(key_type, Enum):
TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\SuperStableDiffusion2.0\TTS-6.0\tts-generation-webui\src\musicgen\musicgen_tab.py", line 208, in generate
    mbd = MultiBandDiffusion.get_mbd_musicgen()
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\audiocraft\models\multibanddiffusion.py", line 74, in get_mbd_musicgen
    models, processors, cfgs = load_diffusion_models(path, device=device)
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\audiocraft\models\loaders.py", line 130, in load_diffusion_models
    model = builders.get_diffusion_model(cfg)
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\audiocraft\models\builders.py", line 213, in get_diffusion_model
    channels = cfg.channels
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\omegaconf\dictconfig.py", line 305, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\omegaconf\base.py", line 95, in _format_and_raise
    format_and_raise(
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\omegaconf\_utils.py", line 644, in format_and_raise
    child_node = node._get_node(key, validate_access=False)
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\omegaconf\dictconfig.py", line 375, in _get_node
    key = self._validate_and_normalize_key(key)
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\omegaconf\dictconfig.py", line 222, in _validate_and_normalize_key
    return self._s_validate_and_normalize_key(self._metadata.key_type, key)
  File "C:\SuperStableDiffusion2.0\TTS-6.0\installer_files\env\lib\site-packages\omegaconf\dictconfig.py", line 241, in _s_validate_and_normalize_key
    elif issubclass(key_type, Enum):
TypeError: issubclass() arg 1 must be a class

**Comment by rsxdalv** [comment]
Hi! No tokens should be required. I saw a similar report recently. MBD had
some sort of incompatibility. I'll look into it and get back to you.

**Comment by rsxdalv** [comment]
Thanks for catching it!

I made a patch for it, so running update will fix it. 
https://github.com/rsxdalv/tts-generation-webui/pull/142

**Comment by Magenta-6** [comment]
Works perfectly. 
And a great improvement to the audio quality!
Thanks man!!
