### ISSUE TITLE
Readme Update? Or Description of each setting popup? 

### ISSUE THREAD

**Issue by Maki9009** [rsxdalv/tts-generation-webui#166]
It is a bit confusing for some of the settings? i don't know what each does or how to work it? 

Like for example: 
Bark:
- I'm very unsure first is empty history? use a voice? use old generation as history? why cant we have a voice selector? like a drop down menu? 

- use V2? but idk if V2 is better or not? 

- Speaker ID? also not sure what that for? or how to use them? 

- Max length of what? its just 15? 15 seconds? 

- I tried a long split prompt.. and it was all broken and idk what I did wrong, i remember while ago i used it worked.. but i forgot how I set it up the first time, 

- whats the difference between Burn in Prompt? and Prompt? and why do I have to use both? 

For Cloning bark 
I'm not sure which tokenizer model is best for what, some i can tell its for a specific language.. but others idk which is good for what 

RVC Beta Demo, might need an upgrade since a lot as been added in terms of pitch collection methods in the original repo such as "rmvpe" 

Tortoise TTS: 
I have no idea how to run it, everytime i try to load in a model it gives an error 
```
Traceback (most recent call last):
  File "E:\RVC\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\RVC\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "E:\RVC\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\RVC\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\RVC\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\RVC\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\RVC\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\gen_tortoise.py", line 49, in switch_model
    get_tts(
  File "E:\RVC\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\gen_tortoise.py", line 84, in get_tts
    MODEL = TextToSpeech(
  File "E:\RVC\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\tortoise\api.py", line 247, in __init__
    self.autoregressive.load_state_dict(torch.load(get_model_path('autoregressive.pth', models_dir)), strict=False)
  File "E:\RVC\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\RVC\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\RVC\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\RVC\\one-click-installers-tts-6.0\\tts-generation-webui\\data\\models\\tortoise\\1001_gpt.pth\\autoregressive.pth'
2023-09-09 11:26:48 | ERROR | asyncio | Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "E:\RVC\one-click-installers-tts-6.0\installer_files\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\RVC\one-click-installers-tts-6.0\installer_files\env\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
``` 
Also why do i have to put the model in a folder? why cant i just drop the file here? 
Im not sure what tokenizer I'm supposed to use? since when i use the inference on MRQ trainer i don't need to select a tokenizer so I'm not sure what I'm supposed to put in. It just works there. 

I like that everything is on this application especially I can move voices from one module to another.. it would make so nice to mix bark or tortoise with RVC for a better output. it's just confusing with its settings.

**Comment by Maki9009** [comment]
Also i think my bark is broken all generated audio that comes out it gibberish it used to work properly.. now idk if its broken from an update or something

**Comment by rsxdalv** [comment]
Gradio doesn't support popups, which is just one of it's many failings. I
began working on a fork of gradio but even then it felt like a time sink.
If you do not have a custom tokenizer, you can just copy the original one.
The reason this repo does it this way is because that's what was enough to
meet the requirements of the users.
I like some things about mrq, and it has a lot of videos on YouTube.
However I can't say that I absolutely love their UX either.
With many of these projects the UX is only tolerable if you have used it
for a long time, have contextual knowledge and maybe extra info from videos
or tutorials.

**Comment by rsxdalv** [comment]
I updated the readme.

Also, thanks for the heads up on RVC. I was tracking an update but now it might be worthwhile to fully integrate it.

**Comment by Maki9009** [comment]
Yeah RVC has a lot going into it now

**Comment by Maki9009** [comment]
im having issues though in using my cloned voice, its very broken.. like that outputs are so yeah maybe it works or it might not work.. and if it does work its so static robotic broken

**Comment by Maki9009** [comment]
Warning for the Horror you are about to hear.... But this is supposed to be a cloned voice of Rick Sanchez on Bark.. he's supposed to say "Hi sir how are you?"

https://github.com/rsxdalv/tts-generation-webui/assets/62298209/9321a272-a4ac-4c7e-830b-9b79bcb27431

**Comment by rsxdalv** [comment]
Oh yes, that's a pretty much failed clone. When you cloned the voice, did the audio clip on the right sound good? I'm thinking if it really could be noise or something like that which caused this.
You can try this as well - use _some_ English male speaker voice as "Semantic" voice and use the clone as "Audio" voice. That's like the newest trick I can offer you.

**Comment by Maki9009** [comment]
the audio clip on the right sounded goodish, like it sounded like my character had a bit of noise/static robotic sound in it, but it wasnt anything that sounded like the clip i sent

**Comment by rsxdalv** [comment]
Did you manage to resolve this problem?
@Maki9009
