### ISSUE TITLE
Problems with installing.

### ISSUE THREAD

**Issue by miraage31** [rsxdalv/tts-generation-webui#178]
I have this issue when I tried installing.

Here is the log:

Env file not found. Creating default env.
Config file not found. Creating default config.
Traceback (most recent call last):
  File "D:\one-click-installers-tts-6.0\tts-generation-webui\server.py", line 40, in <module>
    from src.tortoise.generation_tab_tortoise import generation_tab_tortoise
  File "D:\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\generation_tab_tortoise.py", line 7, in <module>
    from src.tortoise.gen_tortoise import (
  File "D:\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\gen_tortoise.py", line 7, in <module>
    from tortoise.api import TextToSpeech, MODELS_DIR
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\tortoise\api.py", line 7, in <module>
    import torch
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\torch\__init__.py", line 1239, in <module>
    from torch import onnx as onnx
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\torch\onnx\__init__.py", line 12, in <module>
    from . import (  # usort:skip. Keep the order instead of sorting lexicographically
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\torch\onnx\symbolic_caffe2.py", line 4, in <module>
    from torch.onnx import symbolic_helper, symbolic_opset9 as opset9
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\torch\onnx\symbolic_helper.py", line 611, in <module>
    def _onnx_unsupported(op_name: str, value: Optional[_C.Value] = None) -> NoReturn:
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_decor\decorcache.py", line 77, in beartype
    return beartype_object(obj, conf)
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_decor\decorcore.py", line 98, in beartype_object
    _beartype_object_fatal(obj, conf=conf, **kwargs)
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_decor\decorcore.py", line 147, in _beartype_object_fatal
    beartype_nontype(obj, **kwargs)  # type: ignore[return-value]
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_decor\_decormore.py", line 178, in beartype_nontype
    return beartype_func(obj, **kwargs)  # type: ignore[return-value]
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_decor\_decormore.py", line 242, in beartype_func
    func_wrapper_code = generate_code(bear_call)
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_decor\wrap\wrapmain.py", line 187, in generate_code
    code_check_return = _code_check_return(bear_call)
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_decor\wrap\wrapmain.py", line 669, in _code_check_return
    reraise_exception_placeholder(
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_util\error\utilerror.py", line 214, in reraise_exception_placeholder
    raise exception.with_traceback(exception.__traceback__)
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_decor\wrap\wrapmain.py", line 618, in _code_check_return
    ) = make_func_wrapper_code(hint_sane, bear_call.conf, cls_stack)  # type: ignore[assignment]
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_util\cache\utilcachecall.py", line 259, in _callable_cached
    raise exception
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_util\cache\utilcachecall.py", line 251, in _callable_cached
    return_value = args_flat_to_return_value[args_flat] = func(
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_decor\wrap\_wrapcode.py", line 86, in make_func_wrapper_code
    ) = make_check_expr(hint, conf, cls_stack)
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_util\cache\utilcachecall.py", line 259, in _callable_cached
    raise exception
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_util\cache\utilcachecall.py", line 251, in _callable_cached
    return_value = args_flat_to_return_value[args_flat] = func(
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_check\code\codemake.py", line 706, in make_check_expr
    die_if_hint_pep_unsupported(
  File "D:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\beartype\_util\hint\pep\utilpeptest.py", line 205, in die_if_hint_pep_unsupported
    raise BeartypeDecorHintPep484Exception(
beartype.roar.BeartypeDecorHintPep484Exception: Function torch.onnx.symbolic_helper._onnx_unsupported() return PEP 484 type hint "typing.NoReturn" invalid in this type hint context (i.e., "typing.NoReturn" valid only as non-nested return annotation).

**Comment by rsxdalv** [comment]
Thank you for reporting. This matches earlier reports, it seems that some project elsewhere has broken many things. I will research it today.

A helpful user said that reinstalling beartype fixed it, but it didn't seem to work for everyone.
Either way, this seems tricky and needs to be fixed.

**Comment by miraage31** [comment]
Hello just to leave you with an update. The hotfix resolved the issue and everything is working fine. Thanks!
