### ISSUE TITLE
Not even sure what's going wrong

### ISSUE THREAD

**Issue by mqsnn** [rsxdalv/tts-generation-webui#251]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fairseq 0.12.2 requires hydra-core<1.1,>=1.0.7, but you have hydra-core 1.3.2 which is incompatible.
fairseq 0.12.2 requires omegaconf<2.1, but you have omegaconf 2.3.0 which is incompatible.
Successfully installed antlr4-python3-runtime-4.9.3 hydra-core-1.3.2 omegaconf-2.3.0
Checking if node is installed...
v18.16.1
Installing node_modules...

added 480 packages, and audited 481 packages in 19s

146 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (1 low, 4 moderate)

To address issues that do not require attention, run:
  npm audit fix

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
Successfully installed node_modules
Building react-ui...

> tts-generation-webui-react@0.1.0 build
> next build

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
- info Creating an optimized production build  
- info Compiled successfully
- info Linting and checking validity of types  
- info Collecting page data  
[    ] - info Generating static pages (0/18)
Error occurred prerendering page "/history/outputs". Read more: https://nextjs.org/docs/messages/prerender-error
Error: ENOENT: no such file or directory, scandir '/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/outputs'
    at Object.readdirSync (node:fs:1452:3)
    at getDataFromJSON (/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/.next/server/chunks/695.js:92:60)
    at getStaticProps (/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/.next/server/pages/history/[name].js:69:105)
    at /Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/node_modules/next/dist/server/render.js:437:20
    at /Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/node_modules/next/dist/server/lib/trace/tracer.js:113:36
    at NoopContextManager.with (/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/node_modules/next/dist/server/lib/trace/tracer.js:102:107

Error occurred prerendering page "/history/favorites". Read more: https://nextjs.org/docs/messages/prerender-error
Error: ENOENT: no such file or directory, scandir '/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/favorites'
    at Object.readdirSync (node:fs:1452:3)
    at getDataFromJSON (/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/.next/server/chunks/695.js:92:60)
    at getStaticProps (/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/.next/server/pages/history/[name].js:69:105)
    at /Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/node_modules/next/dist/server/render.js:437:20
    at /Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/node_modules/next/dist/server/lib/trace/tracer.js:113:36
    at NoopContextManager.with (/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /Users/masong/one-click-installers-tts-6.0/tts-generation-webui/react-ui/node_modules/next/dist/server/lib/trace/tracer.js:102:107
- info Generating static pages (18/18)

> Export encountered errors on following paths:
	/history/[name]: /history/favorites
	/history/[name]: /history/outputs
Failed to install node_modules
Env file not found. Creating default env.
Config file not found. Creating default config.
Traceback (most recent call last):
  File "/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/server.py", line 40, in <module>
    from src.tortoise.generation_tab_tortoise import generation_tab_tortoise
  File "/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/src/tortoise/generation_tab_tortoise.py", line 7, in <module>
    from src.tortoise.gen_tortoise import (
  File "/Users/masong/one-click-installers-tts-6.0/tts-generation-webui/src/tortoise/gen_tortoise.py", line 7, in <module>
    from tortoise.api import TextToSpeech, MODELS_DIR
  File "/Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/tortoise/api.py", line 10, in <module>
    import torchaudio
  File "/Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import (  # noqa: F401
  File "/Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torchaudio/_extension/__init__.py", line 45, in <module>
    _load_lib("libtorchaudio")
  File "/Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 64, in _load_lib
    torch.ops.load_library(path)
  File "/Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so, 0x0006): Symbol not found: __ZN2at4_ops6conv1d4callERKNS_6TensorES4_RKN3c108optionalIS2_EENS5_8ArrayRefIxEENSA_INS5_6SymIntEEESB_x
  Referenced from: <9018785F-6FE9-3391-92DC-92C02210FCD4> /Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so
  Expected in:     <78DA4C67-8BC7-3995-8324-D2FD95E57BA4> /Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib

Done!

**Comment by mqsnn** [comment]
happens whenever I run start_macos.sh

**Comment by rsxdalv** [comment]
Ok, the main error is:
```
OSError: dlopen(/Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so, 0x0006): Symbol not found: __ZN2at4_ops6conv1d4callERKNS_6TensorES4_RKN3c108optionalIS2_EENS5_8ArrayRefIxEENSA_INS5_6SymIntEEESB_x
Referenced from: <9018785F-6FE9-3391-92DC-92C02210FCD4> /Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so
Expected in: <78DA4C67-8BC7-3995-8324-D2FD95E57BA4> /Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
```
which is related to these issues:
https://github.com/rsxdalv/tts-generation-webui/issues/196
https://github.com/pytorch/audio/issues/62

This might be the fix, run this with cmd_macos.sh
```
conda install -y -k torchaudio=2.0.0 -c pytorch -c nvidia/label/cuda-11.7.0 -c nvidia
```

Also, if I understand correctly, you are running a Mac with an NVidia GPU?

**Comment by rsxdalv** [comment]
As for the big error about /history etc, that has been fixed in the latest patch.

**Comment by mqsnn** [comment]
> Ok, the main error is:
> 
> ```
> OSError: dlopen(/Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so, 0x0006): Symbol not found: __ZN2at4_ops6conv1d4callERKNS_6TensorES4_RKN3c108optionalIS2_EENS5_8ArrayRefIxEENSA_INS5_6SymIntEEESB_x
> Referenced from: <9018785F-6FE9-3391-92DC-92C02210FCD4> /Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so
> Expected in: <78DA4C67-8BC7-3995-8324-D2FD95E57BA4> /Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
> ```
> 
> which is related to these issues: #196 [pytorch/audio#62](https://github.com/pytorch/audio/issues/62)
> 
> This might be the fix, run this with cmd_macos.sh
> 
> ```
> conda install -y -k torchaudio=2.0.0 -c pytorch -c nvidia/label/cuda-11.7.0 -c nvidia
> ```

im sorry im new to all this. how do i run something with a shell script?

**Comment by rsxdalv** [comment]
Run cmd_macos.sh then you will have a window where you can enter the command above.

**Comment by mqsnn** [comment]
when i run "sh cmd_macos.sh" in terminal it gives me this error:

(ttsgen9) masong@masons-Air-2 one-click-installers-tts-6.0 % sh cmd_macos.sh
cmd_macos.sh: line 12: syntax error near unexpected token `('
cmd_macos.sh: line 12: `bash --init-file <(echo "source \"$CONDA_ROOT_PREFIX/etc/profile.d/conda.sh\" && conda activate \"$INSTALL_ENV_DIR\"")'

**Comment by mqsnn** [comment]
Ok i changed the cmd_macos extension to .command and was able to run it. It gave me a bunch of errors, but still allowed me to enter the line you previously gave. I went back to the default term and ran "sh start_macos.sh" and its working now.

**Comment by rsxdalv** [comment]
Ok, I will close this issue. If you have a new problem, feel free to open a new issue.
