### ISSUE TITLE
Terminal errors when clicking "Generate"

### ISSUE THREAD

**Issue by mqsnn** [rsxdalv/tts-generation-webui#252]
2024-01-14 15:02:47 | ERROR | asyncio | Task exception was never retrieved
future: <Task finished name='7lj86rlsnxj_248' coro=<Queue.process_events() done, defined at /Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py:342> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': '7lj86rlsnxj'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing>
Traceback (most recent call last):
  File "/Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 346, in process_events
    client_awake = await self.gather_event_data(event)
  File "/Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 219, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 448, in get_message
    return PredictBody(**data), True
  File "/Users/masong/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': '7lj86rlsnxj'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing

**Comment by rsxdalv** [comment]
Ok, I have seen this error elsewhere but I will see if I can solve this here.

**Comment by rsxdalv** [comment]
I made a new update with a newer gradio version. According to what gradio themselves say, this should be the fix.
Please try updating to the latest version with macos_update.sh
