### ISSUE TITLE
WebUI does not render properly - compared to images I've seen.  And tortoise fails to generate

### ISSUE THREAD

**Issue by jamesdnexa** [rsxdalv/tts-generation-webui#267]
Fresh install of Ubuntu 22.04, with cuda 12.3 and Nvidia driver 535.

Tried this a few times with the latest one click, and the webUI renders in a simple grey background with no formatting.

The only thing notable on installation was some errors with python libs:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
audiocraft 1.3.0a0 requires hydra-core>=1.1, but you have hydra-core 1.0.7 which is incompatible.                                                                                                                 
audiocraft 1.3.0a0 requires torch==2.1.0, but you have torch 2.0.0 which is incompatible.    `

and 

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
audiocraft 1.3.0a0 requires torch==2.1.0, but you have torch 2.0.0 which is incompatible.                                                                                                                         
fairseq 0.12.2 requires hydra-core<1.1,>=1.0.7, but you have hydra-core 1.3.2 which is incompatible.                                                                                                              
fairseq 0.12.2 requires omegaconf<2.1, but you have omegaconf 2.3.0 which is incompatible.     `

Upon install, the webUI allows me to attempt a generation with Tortoise, but the text doesn't get through to the model:

`Traceback (most recent call last):
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/tts-generation-webui/src/tortoise/generation_tab_tortoise.py", line 168, in gen
    yield from generate_tortoise_long(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/tts-generation-webui/src/tortoise/gen_tortoise.py", line 200, in generate_tortoise_long
    datas = generate_tortoise(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/tts-generation-webui/src/tortoise/gen_tortoise.py", line 111, in generate_tortoise
    result, state = tts.tts_with_preset(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/tortoise/api.py", line 321, in tts_with_preset
    return self.tts(text, **settings)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/tortoise/api.py", line 464, in tts
    clip_results = torch.cat(clip_results, dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors
{
  type: 'status',
  endpoint: '/generate_tortoise_1',
  fn_index: 263,
  time: 2024-01-22T20:56:09.818Z,
  queue: true,
  message: null,
  stage: 'error',
  code: undefined,
  success: false
}
`

Many thanks for such a great project and effort

**Comment by jamesdnexa** [comment]
Also just tried out Bark and got a fail, so I'll paste the output here in case it helps:

`Generating: ''' Howdy! '''
Parameters: history_prompt: v2/en_speaker_0 text_temp: 0.7 waveform_temp: 0.7
Traceback (most recent call last):
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/tts-generation-webui/src/bark/generation_tab_bark.py", line 327, in gen
    filename, filename_png, _, _, filename_npz, seed, metadata = generate(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/tts-generation-webui/src/bark/generation_tab_bark.py", line 81, in generate
    full_generation, audio_array = custom_generate_audio(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/tts-generation-webui/src/bark/extended_generate.py", line 53, in custom_generate_audio
    burn_in_prompt_semantic = text_to_semantic(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/bark/api.py", line 25, in text_to_semantic
    x_semantic = generate_text_semantic(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/bark/generation.py", line 394, in generate_text_semantic
    history_prompt = _load_history_prompt(history_prompt)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/bark/generation.py", line 358, in _load_history_prompt
    history_prompt = np.load(history_prompt_input)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'voices\\2023-06-18_21-51-07__bark__continued_generation.npz'
{
  type: 'status',
  endpoint: '/bark',
  fn_index: 140,
  time: 2024-01-22T21:01:06.117Z,
  queue: true,
  message: 'None',
  stage: 'error',
  code: undefined,
  success: false
}
Traceback (most recent call last):
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/gradio/utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/tts-generation-webui/src/tortoise/generation_tab_tortoise.py", line 168, in gen
    yield from generate_tortoise_long(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/tts-generation-webui/src/tortoise/gen_tortoise.py", line 200, in generate_tortoise_long
    datas = generate_tortoise(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/tts-generation-webui/src/tortoise/gen_tortoise.py", line 111, in generate_tortoise
    result, state = tts.tts_with_preset(
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/tortoise/api.py", line 321, in tts_with_preset
    return self.tts(text, **settings)
  File "/home/james/workspace/ttswui/workspace/one-click-installers-tts-6.0/installer_files/env/lib/python3.10/site-packages/tortoise/api.py", line 464, in tts
    clip_results = torch.cat(clip_results, dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors
{
  type: 'status',
  endpoint: '/generate_tortoise_1',
  fn_index: 263,
  time: 2024-01-22T20:56:09.818Z,
  queue: true,
  message: null,
  stage: 'error',
  code: undefined,
  success: false
}

`

**Comment by rsxdalv** [comment]
Thanks for the detailed report. Are you using it with Gradio or react? I'm
guessing Gradio. That tortoise error seems to be specific to what's going
on within the model. Do you have the full tortoise generation parameter
list from command line?

For bark I can see that it's a Unix / vs \ issue. In this case I'll
probably do a path.split then path.join but I'm not near any workstations
for several more days.

**Comment by rsxdalv** [comment]
Ok, I looked at it again and here are some potential answers:

```
Generating: '''Howdy!'''
Parameters:
  history_prompt: v2/en_speaker_0
  text_temp: 0.7
  waveform_temp: 0.7

Traceback (most recent call last):
  File "/path/to/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(…)
  File "/path/to/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(…)
  File "/path/to/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(…)
  File "/path/to/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/path/to/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()

...

FileNotFoundError: [Errno 2] No such file or directory: 'voices/2023-06-18_21-51-07__bark__continued_generation.npz'

...
RuntimeError: torch.cat(): expected a non-empty list of Tensors
```

The bark failed to find the voice, could be for many reasons, but as long as you change the voice it will work fine.

The Tortoise failure with `non-empty list of Tensors` usually means that something was empty, i.e., no prompt or the voice files were empty or the batch size is too small for your GPU.

If there are still any issues, please ask more or reopen this issue.
