### ISSUE TITLE
Issue when 'Use a voice'

### ISSUE THREAD

**Issue by fanverseio** [rsxdalv/tts-generation-webui#27]
So when I try to 'Use a voice' and it will come into an error and gives me this in the terminal:

Traceback (most recent call last):
  File "C:\AI\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict    output = await app.get_blocks().process_api(
  File "C:\AI\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\AI\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\AI\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "C:\AI\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\AI\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\AI\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\AI\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "C:\AI\one-click-installers-tts-4.0\tts-generation-webui\src\bark\generation_tab_bark.py", line 294, in gen
    filename, filename_png, _, _, filename_npz, seed, metadata = generate(
  File "C:\AI\one-click-installers-tts-4.0\tts-generation-webui\src\bark\generation_tab_bark.py", line 77, in generate
    filename, filename_png, filename_npz, metadata = save_generation(
  File "C:\AI\one-click-installers-tts-4.0\tts-generation-webui\src\bark\generation_tab_bark.py", line 130, in save_generation
    history_hash = history_to_hash(history_prompt)
  File "C:\AI\one-click-installers-tts-4.0\tts-generation-webui\src\bark\history_to_hash.py", line 11, in history_to_hash
    "semantic_prompt": npz["semantic_prompt"].tolist(),
TypeError: string indices must be integers

Do you know how to fix this?

**Comment by rsxdalv** [comment]
Fixed it now in bugfix update, my apologies: https://github.com/rsxdalv/tts-generation-webui/commit/ed2abfd1b0eeb11f849ad406a257efc84c5d9808

**Comment by fanverseio** [comment]
Amazing! I just run update_windows.bat and it's all working fine now! Thanks a lot!
