### ISSUE TITLE
Starting doesn't work

### ISSUE THREAD

**Issue by vit-cerny** [rsxdalv/tts-generation-webui#307]
Traceback (most recent call last):
  File "E:\tts-webui\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\requests\compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\tts-webui\one-click-installers-tts-6.0\tts-generation-webui\server.py", line 4, in <module>
    import gradio as gr
  File "E:\tts-webui\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "E:\tts-webui\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "E:\tts-webui\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\components\annotated_image.py", line 9, in <module>
    from gradio_client.documentation import document, set_documentation_group
  File "E:\tts-webui\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio_client\__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "E:\tts-webui\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio_client\client.py", line 22, in <module>
    import requests
  File "E:\tts-webui\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\requests\__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "E:\tts-webui\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\requests\exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "E:\tts-webui\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\requests\compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "E:\tts-webui\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\charset_normalizer\__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "E:\tts-webui\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\charset_normalizer\api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
  File "charset_normalizer\md.py", line 5, in <module>
ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (E:\tts-webui\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\charset_normalizer\constant.py)

Done!
Press any key to continue . . .

**Comment by HDJ-W** [comment]
same problem: solved!

- go to path = one-click-installers-tts-6.0\
 
there in powershell type:
installer_files\env\python3 -m pip install chardet

**Comment by vit-cerny** [comment]
thanks, sorry for being late

**Comment by rsxdalv** [comment]
Hi, I wanted to ask: did you see any installation errors or anything
suspicious when this happened? I am trying to understand if this is an edge
case, a bug or if the installer has broken due to some third party stuff.

**Comment by vit-cerny** [comment]
no errors

**Comment by rsxdalv** [comment]
Strange, hopefully the installer can become more  robust to unknown errors,
thank you.
