### ISSUE TITLE
Docker build failing due to fairseq

### ISSUE THREAD

**Issue by rsxdalv** [rsxdalv/tts-generation-webui#323]
```
#24 10.46   Downloading fairseq-0.12.1.tar.gz (9.6 MB)
#24 10.56      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 103.0 MB/s eta 0:00:00
#24 11.12   Installing build dependencies: started
#24 13.47   Installing build dependencies: finished with status 'done'
#24 13.47   Getting requirements to build wheel: started
#24 13.59   Getting requirements to build wheel: finished with status 'error'
#24 13.60   error: subprocess-exited-with-error
#24 13.60   
#24 13.60   × Getting requirements to build wheel did not run successfully.
#24 13.60   │ exit code: 1
#24 13.60   ╰─> [16 lines of output]
#24 13.60       Traceback (most recent call last):
#24 13.60         File "/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#24 13.60           main()
#24 13.60         File "/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#24 13.60           json_out['return_val'] = hook(**hook_input['kwargs'])
#24 13.60         File "/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
#24 13.60           return hook(config_settings)
#24 13.60         File "/tmp/pip-build-env-ksd6aas7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
#24 13.60           return self._get_build_requires(config_settings, requirements=[])
#24 13.60         File "/tmp/pip-build-env-ksd6aas7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
#24 13.60           self.run_setup()
#24 13.60         File "/tmp/pip-build-env-ksd6aas7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
#24 13.60           exec(code, locals())
#24 13.60         File "<string>", line 27, in <module>
#24 13.60         File "<string>", line 18, in write_version_py
#24 13.60       FileNotFoundError: [Errno 2] No such file or directory: 'fairseq/version.txt'
#24 13.60       [end of output]
```

https://github.com/rsxdalv/tts-generation-webui/actions/runs/9616242480/job/26525293745#step:6:2951

**Comment by rsxdalv** [comment]
Fixed
