### ISSUE TITLE
generation_tab_bark.py TypeError 'shape'

### ISSUE THREAD

**Issue by darus90** [rsxdalv/tts-generation-webui#346]
gradio                 4.38.1

```
Starting server...

Loading extensions:
  Loaded extension: callback_save_generation_ffmpeg
  Loaded extension: callback_save_generation_ffmpeg_flac
  Loaded extension: callback_save_generation_musicgen_ffmpeg
  Loaded extension: callback_save_generation_musicgen_ffmpeg_flac
  Loaded extension: empty_extension
  Loaded 3 callback_save_generation extensions.
  Loaded 2 callback_save_generation_musicgen extensions.
Traceback (most recent call last):
  File "/GAMES/opt/IA_TTS_Generation/tts-generation-webui/server.py", line 59, in <module>
    generation_tab_bark()
  File "/GAMES/opt/IA_TTS_Generation/tts-generation-webui/src/bark/generation_tab_bark.py", line 662, in generation_tab_bark
    *[
     ^
  File "/GAMES/opt/IA_TTS_Generation/tts-generation-webui/src/bark/generation_tab_bark.py", line 663, in <listcomp>
    create_components(
  File "/GAMES/opt/IA_TTS_Generation/tts-generation-webui/src/bark/generation_tab_bark.py", line 811, in create_components
    image = gr.Image(label="Waveform", shape=(None, 100), elem_classes="tts-image")  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/administrador/.local/lib/python3.11/site-packages/gradio/component_meta.py", line 163, in wrapper
    return fn(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: Image.__init__() got an unexpected keyword argument 'shape'
```

**Comment by darus90** [comment]
fixed with gradio==3.48.0
