### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\xd6' in position 265: character maps to <undefined>

### ISSUE THREAD

**Issue by hostolis** [rsxdalv/tts-generation-webui#370]
Hi there, 

**I had a _working_ installation of V6 with no issues at all.**
Last time I used it it was by the end of July.

I tried today to run the start_tts_webui.bat, but while both webuis run (gradio and react), they do not produce the .json file when I generate via bark and I get weird "not found" errors in the console.

It outputs this:

```
 File "C:\Users\_WINDOWSUSERNAME_\tts-generation-webui-main\tts_webui\bark\npz_tools.py", line 50, in join_list
    return "".join(x)
TypeError: can only join an iterable
{
  type: 'status',
  endpoint: '/bark',
  fn_index: 17,
  time: 2024-09-02T11:45:54.984Z,
  queue: true,
  message: null,
  visible: undefined,
  duration: undefined,
  stage: 'error',
  code: undefined,
  success: false
}
Traceback (most recent call last):
  File "C:\Users\_WINDOWSUSERNAME_\tts-generation-webui-main\installer_files\env\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\_WINDOWSUSERNAME_\tts-generation-webui-main\installer_files\env\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\_WINDOWSUSERNAME_\tts-generation-webui-main\installer_files\env\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\_WINDOWSUSERNAME_\tts-generation-webui-main\installer_files\env\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\_WINDOWSUSERNAME_\tts-generation-webui-main\installer_files\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\_WINDOWSUSERNAME_\tts-generation-webui-main\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\_WINDOWSUSERNAME_\tts-generation-webui-main\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\_WINDOWSUSERNAME_\tts-generation-webui-main\installer_files\env\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\_WINDOWSUSERNAME_\tts-generation-webui-main\tts_webui\history_tab\main.py", line 169, in select_audio_history
    return _select_audio_history(*_select_audio(table, evt))
  File "C:\Users\_WINDOWSUSERNAME_\tts-generation-webui-main\tts_webui\history_tab\main.py", line 29, in _select_audio
    with open(filename.replace(".wav", ".json")) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs\\2024-09-02_14-45-54__bark__Hello_Can_you_s\\2024-09-02_14-45-54__bark__Hello_Can_you_s.json'
```

In the attached diagnostic, I see a weird error about encoding:

```UnicodeEncodeError: 'charmap' codec can't encode character '\xd6' in position 265: character maps to <undefined>```

[diagnostic.txt](https://github.com/user-attachments/files/16837744/diagnostic.txt)

Since I didn't care about losing my setup, I wiped everything from the installation folder and I redownloaded the main.zip archive, and ran the start_tts_webui.bat inside the tts-generation-webui-main folder and it redownloaded everything.
Same errors...

I run Windows 11, on a ryzen 7 7800x3d and an RTX 4090.

**Comment by rsxdalv** [comment]
Thanks for the detailed report. I was able to reproduce the issue and have pushed a bugfix, it will be automatically downloaded when you run start_tts_webui.bat.

As for the diagnostic failing, that seems complicated so at the moment I am hoping I do not need to debug that.

**Comment by hostolis** [comment]
Oh wow, that was fast!
