### ISSUE TITLE
Parler-TTS Extension Issue

### ISSUE THREAD

**Issue by nandakho** [rsxdalv/tts-generation-webui#372]
Hi, I notice you have added Parler-TTS extension recently (#366).

However, after installing it and restarting webui, i got this error:
```
Loading Parler-TTS Extension...
Failed to load Parler-TTS Extension tab. Please check your configuration.
Error: No package metadata was found for extension_parler_tts
Stacktrace: Traceback (most recent call last):
  File "N:\tts-generation-webui\tts_webui\extensions_loader\interface_extensions.py", line 34, in _handle_package
    package_version = version(package_name)
  File "N:\tts-generation-webui\installer_files\env\lib\importlib\metadata\__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "N:\tts-generation-webui\installer_files\env\lib\importlib\metadata\__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "N:\tts-generation-webui\installer_files\env\lib\importlib\metadata\__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for extension_parler_tts
```

After troubleshooting a bit,
I found out that [setup.py](https://github.com/rsxdalv/extension_parler_tts/blob/main/setup.py) is a template of your extension's setup.py and hasn't been changed to Parler-TTS yet.

I have created a PR for this, and tested works on my local (Windows 11 OS).
I haven't check dependency conflicts for other extension though.

**Comment by rsxdalv** [comment]
Thank you for the fix, it has been merged!
