### ISSUE TITLE
macOS install issue

### ISSUE THREAD

**Issue by zlever01** [rsxdalv/tts-generation-webui#51]
The installer works fine for windows but I get this error when installing on macOS: 

```
Retrieving notices: ...working... done
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Traceback (most recent call last):
  File "/Users/Downloads/one-click-installers-tts-4.0/webui.py", line 125, in <module>
    install_dependencies()
  File "/Users/Downloads/one-click-installers-tts-4.0/webui.py", line 63, in install_dependencies
    update_dependencies()
  File "/Users/Downloads/one-click-installers-tts-4.0/webui.py", line 77, in update_dependencies
    os.chdir("tts-generation-webui/models/bark")
FileNotFoundError: [Errno 2] No such file or directory: 'tts-generation-webui/models/bark'
```

After manually adding the required directories and files, I get this error:

```
/System/Volumes/Preboot/Cryptexes/OS/Users/Downloads/one-click-installers-tts-4.0/installer_files/env/lib/python3.10/site-packages/torch/lib/libtorch_global_deps.dylib' (no such file), 
'/Users/Downloads/one-click-installers-tts-4.0/installer_files/env/lib/python3.10/site-packages/torch/lib/libtorch_global_deps.dylib' 
(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by rsxdalv** [comment]
Hi, thank you for debugging this. I will research why it's installing the
wrong architecture.

**Comment by rsxdalv** [comment]
I haven't seen a perfect solution yet. I have a few questions:
* Do other projects, such as Automatic1111 stable diffusion or oobabooga text generation webui work?
* Is this a M1 Chip?
* If you try to install again, would it be possible to get the installation logs?

**Comment by zlever01** [comment]
Thanks, it is a M1 chip. I found these mac instructions from oobabooga/text-generation-webui: [MacOS users: 393](https://github.com/oobabooga/text-generation-webui/pull/393) and this [video](https://www.youtube.com/watch?v=btmVhRuoLkc) as a guide.
This got me further with installing the correct version of tourch for the M1 chip, but now I get this error: 
```
      building 'xformers._C' extension
      creating build/temp.macosx-10.9-x86_64-cpython-310
      creating build/temp.macosx-10.9-x86_64-cpython-310/xformers
      creating build/temp.macosx-10.9-x86_64-cpython-310/xformers/csrc
      creating build/temp.macosx-10.9-x86_64-cpython-310/xformers/csrc/attention
      creating build/temp.macosx-10.9-x86_64-cpython-310/xformers/csrc/attention/autograd
      creating build/temp.macosx-10.9-x86_64-cpython-310/xformers/csrc/attention/cpu
      creating build/temp.macosx-10.9-x86_64-cpython-310/xformers/csrc/indexing
      creating build/temp.macosx-10.9-x86_64-cpython-310/xformers/csrc/swiglu
 clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/user/opt/anaconda3/envs/turtoise/include -fPIC -O2 -isystem /Users/user/opt/anaconda3/envs/turtoise/include -I/private/var/folders/bb/q0dc1__902zgw90js28ydjv80000gn/T/pip-install-lpe7a_vz/xformers_80db52e7b5e74a9ab14d5b4accfd94a7/xformers/csrc -I/Users/user/opt/anaconda3/envs/turtoise/lib/python3.10/site-packages/torch/include -I/Users/user/opt/anaconda3/envs/turtoise/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/Users/user/opt/anaconda3/envs/turtoise/lib/python3.10/site-packages/torch/include/TH -I/Users/user/opt/anaconda3/envs/turtoise/lib/python3.10/site-packages/torch/include/THC -I/Users/user/opt/anaconda3/envs/turtoise/include/python3.10 -c xformers/csrc/attention/attention.cpp -o build/temp.macosx-10.9-x86_64-cpython-310/xformers/csrc/attention/attention.o -O3 -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_clang\" -DPYBIND11_STDLIB=\"_libcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1002\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
      clang: error: unsupported option '-fopenmp'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xformers
  Running setup.py clean for xformers
Successfully built audiocraft tortoise
Failed to build xformers
ERROR: Could not build wheels for xformers, which is required to install pyproject.toml-based projects

```

**Comment by rsxdalv** [comment]
Also, to clarify - M1 chips don't need the "xformers" (it's for accelerating NVIDIA GPU workflows), so once the projects get cleaned up it shouldn't even try to install it.

**Comment by zlever01** [comment]
Yeah, it does completely halt the ability to use the app. A modular install would be great if audiocraft is a no go.

**Comment by rsxdalv** [comment]
Try the new installer and the newest update please.

**Comment by rsxdalv** [comment]
Hopefully now it installs as much as it can and runs, I'll close this particular issue for now. (Also because the installation scripts have changed.)

For future Mac installation issues, please open new issues.
