### ISSUE TITLE
how much vram do i need i got 6gb

### ISSUE THREAD

**Issue by rekilla** [rsxdalv/tts-generation-webui#56]
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Loading extensions:
Loaded extension: callback_save_generation_ffmpeg
Loaded extension: callback_save_generation_musicgen_ffmpeg
Loaded extension: empty_extension
Loaded 2 callback_save_generation extensions.
Loaded 1 callback_save_generation_musicgen extensions.
Loading Bark models
        - Text Generation:               GPU: Yes, Small Model: Yes
        - Coarse-to-Fine Inference:      GPU: Yes, Small Model: Yes
        - Fine-tuning:                   GPU: Yes, Small Model: No
        - Codec:                         GPU: Yes
Traceback (most recent call last):
  File "D:\AI\TTS\one-click-installers-tts-4.0\tts-generation-webui\server.py", line 13, in <module>
    from src.bark.generation_tab_bark import generation_tab_bark
  File "D:\AI\TTS\one-click-installers-tts-4.0\tts-generation-webui\src\bark\generation_tab_bark.py", line 27, in <module>
    from src.model_manager import model_manager
  File "D:\AI\TTS\one-click-installers-tts-4.0\tts-generation-webui\src\model_manager.py", line 4, in <module>
    model_manager = BarkModelManager(config)
  File "D:\AI\TTS\one-click-installers-tts-4.0\tts-generation-webui\src\bark\BarkModelManager.py", line 8, in __init__
    self.reload_models(config)
  File "D:\AI\TTS\one-click-installers-tts-4.0\tts-generation-webui\src\bark\BarkModelManager.py", line 29, in reload_models
    preload_models(
  File "D:\AI\TTS\one-click-installers-tts-4.0\tts-generation-webui\models\bark\bark\generation.py", line 327, in preload_models
    _ = load_model(
  File "D:\AI\TTS\one-click-installers-tts-4.0\tts-generation-webui\models\bark\bark\generation.py", line 275, in load_model
    model = _load_model_f(ckpt_path, device)
  File "D:\AI\TTS\one-click-installers-tts-4.0\tts-generation-webui\models\bark\bark\generation.py", line 240, in _load_model
    model.to(device)
  File "D:\AI\TTS\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "D:\AI\TTS\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\AI\TTS\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\AI\TTS\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "D:\AI\TTS\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "D:\AI\TTS\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 5.25 GiB already allocated; 0 bytes free; 5.35 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by rsxdalv** [comment]
6gb can do it. You can try just setting the fine model to small in the bark
settings, I believe it's named like:
Use small model for fine inference
If you want to save more VRAM (there is some tradeoff) you can go ahead and
turn on CPU offloading. That will consume more RAM but then you can get
down to like 2-3gbs for bark.

**Comment by rekilla** [comment]
okay but how do i do that, cause the error is after I start the bat file I can't get to webui...im new to this can u tell me which file to change

**Comment by rsxdalv** [comment]
config.json
And thanks for the report, I will make the loading fail safe

**Comment by rsxdalv** [comment]
Ok, the newest update will report an error but still load the UI if there's not enough VRAM. Please run update_windows.bat.
(PR https://github.com/rsxdalv/tts-generation-webui/pull/58)

**Comment by rekilla** [comment]
thank man works now..its a dope thing u made will let u know if I find any more bugs
