### ISSUE TITLE
Microsoft Visual C++ required now? Seriously?

### ISSUE THREAD

**Issue by mweldon** [rsxdalv/tts-generation-webui#61]
Okay I installed it and update still says that I need it. The installer took about 15 minutes and threw a million errors. After re-running it several times I finally get through it and it says "No GPU being used". Try to run the update bat and 15 minutes later it complains that I don't have MSVC. So I install that, try to update again and it still thinks I don't have it.

**Comment by rsxdalv** [comment]
Microsoft visual C++ requirement happens when some package isn't available
in binary format. Sometimes these packages can be installed with an
alternative command. But it is necessary to know which package is
causing the issue.

They are complied to binary for optimization; however some of the code
isn't even fully python thus requires a compiler as a matter of fact.

Microsoft Visual C++ is the standard C++ compiler on Windows. It's similar
to GCC for Linux. The installer allows only for the build tools to be
installed, and automatically sets up the path.

In any case, there appears to be a major failure on your system that
requires installation logs to debug.

**Comment by mweldon** [comment]
I know what MSVC is. If I have to build the libraries from scratch, that's probably a deal-breaker for me.

Here's one of the errors:

  Building wheel for scikit-learn (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for scikit-learn (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      <string>:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Partial import of sklearn during the build process.
      <string>:116: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html


      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      Traceback (most recent call last):
        File "C:\Users\Mike\Documents\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Mike\Documents\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Mike\Documents\one-click-installers-tts-4.0\installer_files\env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "D:\Temp\pip-build-env-zu8s98wd\overlay\Lib\site-packages\setuptools\build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "D:\Temp\pip-build-env-zu8s98wd\overlay\Lib\site-packages\setuptools\build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "D:\Temp\pip-build-env-zu8s98wd\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "D:\Temp\pip-build-env-zu8s98wd\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 306, in <module>
        File "<string>", line 302, in setup_package
        File "D:\Temp\pip-build-env-zu8s98wd\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
          config = configuration()
        File "<string>", line 188, in configuration
        File "D:\Temp\pip-build-env-zu8s98wd\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 1050, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "D:\Temp\pip-build-env-zu8s98wd\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 1016, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "D:\Temp\pip-build-env-zu8s98wd\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 958, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "D:\Temp\pip-install-17ltkrap\scikit-learn_b2e015754953467d826c860f6fd2daf1\sklearn\setup.py", line 83, in configuration
          cythonize_extensions(top_path, config)
        File "D:\Temp\pip-install-17ltkrap\scikit-learn_b2e015754953467d826c860f6fd2daf1\sklearn\_build_utils\__init__.py", line 45, in cythonize_extensions
          basic_check_build()
        File "D:\Temp\pip-install-17ltkrap\scikit-learn_b2e015754953467d826c860f6fd2daf1\sklearn\_build_utils\pre_build_helpers.py", line 106, in basic_check_build
          compile_test_program(code)
        File "D:\Temp\pip-install-17ltkrap\scikit-learn_b2e015754953467d826c860f6fd2daf1\sklearn\_build_utils\pre_build_helpers.py", line 66, in compile_test_program
          ccompiler.compile(['test_program.c'], output_dir='objects',
        File "D:\Temp\pip-build-env-zu8s98wd\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
          self.initialize()
        File "D:\Temp\pip-build-env-zu8s98wd\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "D:\Temp\pip-build-env-zu8s98wd\overlay\Lib\site-packages\setuptools\msvc.py", line 214, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "D:\Temp\pip-build-env-zu8s98wd\overlay\Lib\site-packages\setuptools\msvc.py", line 168, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
  Building wheel for fairseq (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for fairseq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1423 lines of output]

**Comment by mweldon** [comment]
Trying to build this one too:

```
building 'fairseq.libbleu' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

**Comment by rsxdalv** [comment]
Thanks for the logs. I'll try some different scenarios to test it out.
Although some libraries are true snowflakes, I think others can be
prebuilt.

Fairseq failing to build will only disable the voice cloning tab.
Unfortunately this seems to be a poorly distributed package, I've heard
about it failing in other projects and especially when there's even a hint
of uniqueness in the user's system.

**Comment by rsxdalv** [comment]
Ok, so the wheels are being built for new versions of scikit-learn
(https://github.com/scikit-learn/scikit-learn/blob/main/.github/workflows/wheels.yml)
And in fact one of them is being installed; 
```
Collecting scikit-learn>=0.20.0 (from librosa->audiocraft@ git+https://git@github.com/facebookresearch/audiocraft#egg=audiocraft@c9179f8->-r requirements.txt (line 8))
  Downloading scikit_learn-1.3.0-cp310-cp310-win_amd64.whl (9.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 45.2 MB/s eta 0:00:00
```
however, there's a dependency that requires an old version:
```
Collecting scikit-learn==0.24.0 (from audiolm-pytorch->-r requirements.txt (line 1))
```

Which then causes it to get built
```
Building wheels for collected packages: scikit-learn
  Building wheel for scikit-learn (pyproject.toml) ... done
  Created wheel for scikit-learn: filename=scikit_learn-0.24.0-cp310-cp310-win_amd64.whl size=6091609 sha256=d2ffa30a55acfe172e9071ed14a2a6ee0e22b9097f34f98484568f9e5071769e
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\ae\58\c2\13fa991d6624a58064aeaf1b949900a3dcdb4ca046b75f19e8
Successfully built scikit-learn
```

Therefore fixing some downstream project might be enough to deal with this.
Additionally, the installation process of tts-generation-webui could be simplified altogether by modifying some of the downstream projects.

Since it also affects fairseq, this is the project I will attempt to package and fix:
https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer

**Comment by rsxdalv** [comment]
I added nodejs to the new installer, although I have not confirmed if it automatically includes the build tools when installed this way. However, if manually installed, nodejs does include the build tools (an oddly is a friendlier install than the official way).

**Comment by AIhasArrived** [comment]
Hello @mweldon  I have spent 3 entire weeks trying to find a way to clone correclty voices and I still did not get good results, I am so tired of it. I am contacting you because I saw you had old comments under old issues, you haev probably found better ways since then? Could you save me from my misery and direct me towards a method, a repo, a tutorial or anything that helps get to the point where I can actually clone a voice thats looks similar to the cloned voice please?  Help my soul lol. Really.
