### ISSUE TITLE
Massive amount of both dependency errors and tracebacks related either to Windows 11 or an unsupported GPU while installing "oogabooga", the same problem occurs while installing the "tts-generation-webui"

### ISSUE THREAD

**Issue by Incognitiv** [rsxdalv/tts-generation-webui#81]
OS: Windows 11
GPU: GeForce 1650 (no Ti, anything like that)
Problem(s):

**The very first error occured while installing the one-click-installer package itself:**
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
open-clip-torch 2.7.0 requires protobuf==3.20.0, but you have protobuf 4.23.4 which is incompatible.
rembg 2.0.35 requires scikit-image>=0.19.3, but you have scikit-image 0.19.2 which is incompatible.
tensorflow-intel 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.23.4 which is incompatible.
tensorflow-intel 2.11.0 requires tensorboard<2.12,>=2.11, but you have tensorboard 2.13.0 which is incompatible.
audiocraft 0.0.2a2 requires hydra-core>=1.1, but you have hydra-core 1.0.7 which is incompatible.
Successfully installed Cython-0.29.36 Pillow-9.3.0 Werkzeug-2.3.6 absl-py-1.4.0 faiss-cpu-1.7.4 functorch-2.0.0 json5-0.9.14 librosa-0.9.2 llvmlite-0.39.0 matplotlib-inline-0.1.6 praat-parselmouth-0.4.3 protobuf-4.23.4 pyworld-0.3.3 resampy-0.4.2 rvc-beta-0.1.1 tensorboard-2.13.0 tensorboardX-2.6.1 torchcrepe-0.0.20 torchgen-0.0.1 tornado-6.3.2 traitlets-5.9.0 uvicorn-0.21.1
```

```
[notice] A new release of pip is available: 23.1.2 -> 23.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Successfully installed RVC dependencies
Env file not found. Creating default env.
Config file not found. Creating default config.
Traceback (most recent call last):
  File "X:\tts_gen_webui\oobabooga_windows\installer_files\env\lib\site-packages\tensorboard\compat\__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (X:\Bark\one-click-installers-tts-6.0\tts_gen_webui\oobabooga_windows\installer_files\env\lib\site-packages\tensorboard\compat\__init__.py)
```

**After I tried to run it "anyway":**
```
Traceback (most recent call last):
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\tensorboard\compat\__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (X:\tts_gen_webui\installer_files\env\lib\site-packages\tensorboard\compat\__init__.py)
```

**During handling of the above exception, another exception occurred:**

```
Traceback (most recent call last):
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\transformers\utils\import_utils.py", line 1172, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "X:\tts_gen_webui\installer_files\env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\transformers\models\gpt2\modeling_gpt2.py", line 38, in <module>
    from ...modeling_utils import PreTrainedModel, SequenceSummary
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 84, in <module>
    from accelerate import __version__ as accelerate_version
  File "C:\Users\Shiny\AppData\Roaming\Python\Python310\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\Shiny\AppData\Roaming\Python\Python310\site-packages\accelerate\accelerator.py", line 37, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "C:\Users\Shiny\AppData\Roaming\Python\Python310\site-packages\accelerate\tracking.py", line 42, in <module>
    from torch.utils import tensorboard
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\torch\utils\tensorboard\writer.py", line 16, in <module>
    from ._embedding import (
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\torch\utils\tensorboard\_embedding.py", line 9, in <module>
    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\tensorboard\lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\tensorboard\lazy.py", line 50, in load_once
    module = load_fn()
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\tensorboard\compat\__init__.py", line 45, in tf
    import tensorflow
  File "C:\Users\Shiny\AppData\Roaming\Python\Python310\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Shiny\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Shiny\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\eager\context.py", line 28, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Users\Shiny\AppData\Roaming\Python\Python310\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\Users\Shiny\AppData\Roaming\Python\Python310\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\Users\Shiny\AppData\Roaming\Python\Python310\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\Users\Shiny\AppData\Roaming\Python\Python310\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\Users\Shiny\AppData\Roaming\Python\Python310\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "X:\tts_gen_webui\tts-generation-webui\server.py", line 40, in <module>
    from src.tortoise.generation_tab_tortoise import generation_tab_tortoise
  File "X:\tts_gen_webui\tts-generation-webui\src\tortoise\generation_tab_tortoise.py", line 7, in <module>
    from src.tortoise.gen_tortoise import (
  File "X:\tts_gen_webui\tts-generation-webui\src\tortoise\gen_tortoise.py", line 7, in <module>
    from tortoise.api import TextToSpeech, MODELS_DIR
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\tortoise\api.py", line 14, in <module>
    from tortoise.models.autoregressive import UnifiedVoice
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\tortoise\models\autoregressive.py", line 6, in <module>
    from transformers import GPT2Config, GPT2PreTrainedModel, LogitsProcessorList
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\transformers\utils\import_utils.py", line 1163, in __getattr__
    value = getattr(module, name)
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\transformers\utils\import_utils.py", line 1162, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "X:\tts_gen_webui\installer_files\env\lib\site-packages\transformers\utils\import_utils.py", line 1174, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.gpt2.modeling_gpt2 because of the following error (look up to see its traceback):
Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by rsxdalv** [comment]
Oh no. Thanks for the report, I'll see if I can ping some downstream
projects. And my best suggestion at the moment would be to give WSL a try.
It might not work, but if it does it does.

**Comment by rsxdalv** [comment]
As for the pip complaining about dependencies, yes, that is the state of python. Python does not allow multiple versions to be installed at the same time, and packages are frequently unnecessarily specific with their "requirements".
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
open-clip-torch 2.7.0 requires protobuf==3.20.0, but you have protobuf 4.23.4 which is incompatible.
rembg 2.0.35 requires scikit-image>=0.19.3, but you have scikit-image 0.19.2 which is incompatible.
tensorflow-intel 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.23.4 which is incompatible.
tensorflow-intel 2.11.0 requires tensorboard<2.12,>=2.11, but you have tensorboard 2.13.0 which is incompatible.
audiocraft 0.0.2a2 requires hydra-core>=1.1, but you have hydra-core 1.0.7 which is incompatible.
Successfully installed Cython-0.29.36 Pillow-9.3.0 Werkzeug-2.3.6 absl-py-1.4.0 faiss-cpu-1.7.4 functorch-2.0.0 json5-0.9.14 librosa-0.9.2 llvmlite-0.39.0 matplotlib-inline-0.1.6 praat-parselmouth-0.4.3 protobuf-4.23.4 pyworld-0.3.3 resampy-0.4.2 rvc-beta-0.1.1 tensorboard-2.13.0 tensorboardX-2.6.1 torchcrepe-0.0.20 torchgen-0.0.1 tornado-6.3.2 traitlets-5.9.0 uvicorn-0.21.1
```

Also I'm testing with a GTX1070 so a 16 series should be supported.

**Comment by AIhasArrived** [comment]
Hello @Incognitiv 
 I have spent 3 entire weeks trying to find a way to clone correclty voices and I still did not get good results, I am so tired of it. I am contacting you because I saw you had old comments under old issues, you haev probably found better ways since then? Could you save me from my misery and direct me towards a method, a repo, a tutorial or anything that helps get to the point where I can actually clone a voice thats looks similar to the cloned voice please?  Help my soul lol. Really.
