### ISSUE TITLE
Error Tortoise with corrupted regresive model

### ISSUE THREAD

**Issue by brehiner** [rsxdalv/tts-generation-webui#84]
I was making my first test with tortoise model and this started to download all requirements to generate the audio but my hard disk get full and this operation could not be finished and get me an error, so I restarted the application and the error still were there, so I delete all the folder for trying to fix the problem, then I reinstall everything once more but the issue still keeps, that means that the installation of the regresive model of tortoise is in a folder out of the application, can you say me where can I find this corrupted file?

Generating tortoise with params:
TortoiseParameters(
    text='hello world',
    voice='random',
    preset='ultra_fast',
    seed=-1.0,
    cvvp_amount=0.0,
    split_prompt=False,
    num_autoregressive_samples=16,
    diffusion_iterations=30,
    temperature=0.8,
    length_penalty=1.0,
    repetition_penalty=2.0,
    top_p=0.8,
    max_mel_tokens=500,
    cond_free=True,
    cond_free_k=2,
    diffusion_temperature=1.0,
    model='Default'
)
Traceback (most recent call last):
  File "C:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "C:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "C:\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\generation_tab_tortoise.py", line 162, in gen
    yield from generate_tortoise_long(
  File "C:\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\gen_tortoise.py", line 188, in generate_tortoise_long
    datas = generate_tortoise(
  File "C:\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\gen_tortoise.py", line 100, in generate_tortoise
    tts = get_tts()
  File "C:\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\gen_tortoise.py", line 77, in get_tts
    MODEL = TextToSpeech(
  File "C:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\tortoise\api.py", line 237, in __init__
    self.diffusion.load_state_dict(torch.load(get_model_path('diffusion_decoder.pth', models_dir)))
  File "C:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by rsxdalv** [comment]
Yes, it's a separate folder, I'll find it in a minute. I recommend checking
your .cache in your user profile, it contains many models, not just from
this UI.

**Comment by brehiner** [comment]
Thank you so much!!! your answer was very clear and fast
