### ISSUE TITLE
Convert RVC error 

### ISSUE THREAD

**Issue by sergedahdouh** [rsxdalv/tts-generation-webui#96]
when i press generate i am receiving an error 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/content/tts-generation-webui/src/rvc_tab/rvc_tab.py", line 72, in run_rvc
    index_path=index_path.name,
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by rsxdalv** [comment]
This could happen when there's no index selected. Perhaps there was an issue for the selection process. Could you try drag and dropping it or selecting it manually as the file?
If there's still an issue, could you please make a screenshot so I can see the state of the UI?

**Comment by rsxdalv** [comment]
Closing this as https://github.com/rsxdalv/tts-generation-webui/issues/95 has more details.
